package: markitup
version: '3.8.0-beta1'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/markitup

page:
    title: 'translate:title'
    perm: markitup[]
    pjax: true
    subpages:
        profiles: 
            title: 'translate:profiles'
            perm: 'markitup[profiles]'
        snippets: 
            title: 'translate:snippets'
            perm: 'markitup[snippets]'
        overview: 
            title: 'translate:description'
            subPath: README.md

conflicts:
    packages:
        textile: '*'

requires:
    php:
        version: '>=8.1'
    redaxo: '^5.15.0'