package: markitup
version: '3.8.0-beta1'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/markitup

page:
    title: 'translate:title'
    perm: markitup[]
    pjax: true
    subpages:
        profiles: 
            title: 'translate:profiles'
            perm: 'markitup[profiles]'
        snippets: 
            title: 'translate:snippets'
            perm: 'markitup[snippets]'
        overview: 
            title: 'translate:description'
            subPath: README.md
        manual: 
            title: 'translate:manual'
            icon: rex-icon fa-book
            perm: 'admin[]'
            subpages:
                intro:
                    title: 'translate:markitup_manual_intro'
                    icon: rex-icon rex-icon-info
                    subPath: main_intro.md
                textile:
                    title: 'translate:markitup_manual_textile'
                    icon: rex-icon rex-icon-article
                    subPath: howto_textile.md
                markdown:
                    title: 'translate:markitup_manual_markdown'
                    icon: rex-icon rex-icon-article
                    subPath: howto_markdown.md
                developer:
                    title: 'translate:markitup_manual_developer'
                    icon: rex-icon fa-code
                    subPath: howto_integration.md

conflicts:
    packages:
        textile: '*'

requires:
    redaxo: '^5.2.0'
